name: Build & deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PUBLIC_URL: https://rbtying.github.io/letter-boxed-solver/

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./letter-boxed-solver-ui
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Node.js ⚙️
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'yarn'

    - name: Install dependencies 📦
      run: yarn install --frozen-lockfile
    
    - name: Build project
      run: yarn build

    - name: Upload production-ready build files
      uses: actions/upload-artifact@v2
      with:
        name: production-files
        path: ./letter-boxed-solver-ui/build
  
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./letter-boxed-solver-ui
        
    if: github.ref == 'refs/heads/master'
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: production-files
        path: ./build

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
